### ISSUE TITLE
Finalize Early Bird and Pre-Sale Details

### ISSUE THREAD

**Issue by brianlenz** [NarrativeNetwork/tokensale-smartcontract#7]
We need to finalize the Early Bird and Pre-Sale details and update the contract accordingly:

* `minInvestment` for Early Bird and Pre-Sale (currently set to the same as the main sale at 0.2)
* Total sale duration. This will be used to determine the `endBlock` in `start()`. We'll also need to update `adjustDuration()` accordingly (e.g. total sale duration plus 10 days).

There are todos for these as appropriate in the code from #6.

**Comment by brianlenz** [comment]
Per NarrativeNetwork/tokensale-registration#52, we'll set the limit for the Early Bird (Private Pre-Sale) to 110eth.

**Comment by brianlenz** [comment]
Here's the new schedule:

*Private Pre-Sale*

The private pre-sale technically is available any time, so I'll need to consider that when making tweaks here.

Minimum Contribution: 100 ETH

*Public Pre-Sale*

Start: February 7, 2018 5:00 PM UTC
End: February 14, 2018 9:00 PM UTC

Minimum Contribution: 10 ETH

*Token Sale*

Start: Feb 15, 2018 at 5:00 PM UTC
End: March 22, 2018 at 9:00 PM UTC

**Comment by brianlenz** [comment]
@ted-oneill, FYI, the current contract is set to limit the private pre-sale to 9000 ETH at most and the public pre-sale to 60000 ETH at most. Do you have an idea of what you'd like those limits adjusted to?

**Comment by ted-oneill** [comment]
Let's make max round limit 25,000 ETH for both the private and public pre-sales. (The price of ETH has more than doubled since we put those limits in place.)

I don't suppose there is any way for us to adjust the caps after the contract is deployed is there?  If ETH were to double between now and the token sale, for instance, we could conceivably oversell.

**Comment by brianlenz** [comment]
That's a really good point. We don't have any token-based limits set on phase one or phase two since we can't (without the exchange rate being set at the start of the main sale).

As the contract is written currently, there is no way to change the ETH contribution limits. I'm not sure that will be necessary, though, as we can always stop the sale at any point (e.g. if it looks like we're getting in danger of an oversale happening). I think that if we just keep an eye on the exchange rate and total contributions over the course of the pre-sales, that should be sufficient.

Do you think that would work?

**Comment by brianlenz** [comment]
In terms of the pre-sale contribution limits, the way the contract is structured, we set an initial limit for round one, and then set a separate limit for round two (which is a limit for the combined total of rounds one and two). As such, I propose that the round one limit is 25,000 ETH and therefore the round two limit would be 50,000 ETH. This means that if 10,000 ETH are contributed during round one, then up to 40,000 ETH could be contributed during round two.

Does that sound good?

**Comment by brianlenz** [comment]
As discussed in Slack, we'll use Thursday Dec. 21 for the Private Pre-Sale start. I'm proposing 9PM UTC (4pm ET / 1pm PT):

December 21, 2017 9:00 PM UTC

That means the sale will be exactly 91 days long. We'll allow extending the sale duration up to 101 days total (91+10) based on an average expected block rate of 4.3 blocks/minute.

**Comment by ted-oneill** [comment]
Well I'd be concerned about a limit of 50,000, even knowing that we can technically stop the sale anytime. At the current exchange rate, we would be overselling the tokens. :) 

That's why I want to have a high limit for Phase 1, since that is when high rollers might want to come in, and if we happen to sell that out, we simply would not have a Phase 2 (it would already be sold out).

How about we go with 30k for each phase; that gives us some protection if ETH prices plummet, and then we would just need to make sure we do not oversell if the prices rise significantly. And yes, I understand that if we sold 30k in phase 1 then phase 2 would already be capped out.

**Comment by brianlenz** [comment]
OK, I guess I misunderstood you, that's all :D We can certainly use a single limit that covers both phases if you'd prefer that. I'll set it to 30k.
